### ISSUE TITLE
Stackoverflow getUnit/get

### ISSUE THREAD

**Issue by IliaEremin** [stefanhaustein/HtmlView2#6]
Here is my code:
```
String html = String.format("<html><head><style type=\"text/css\">%s</style></head><body>%s</body></html>", css, block.getData());
            try {
                Reader reader = new StringReader(html);
                htmlProcessor.parse(reader, uiHtmlView);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
```

```
  java.lang.StackOverflowError
            at org.kobjects.css.CssStyleDeclaration.getUnit(CssStyleDeclaration.java:333)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:165)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:102)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:217)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:102)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:217)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:102)
            at org.kobjects.css.CssStyleDeclaration.get(CssStyleDeclaration.java:217)
```

**Comment by stefanhaustein** [comment]
What's the content of the css variable in this case?

**Comment by IliaEremin** [comment]
it's following:
```
body {
    padding: 0px;
    font: 110%/1.5em Helvetica, Arial, sans-serif;
    color: #000;
    background: #fff;
}
\n\nh1 {
    font-size: 1.4em;
    line-height: 1.3em;
    padding: 0em;
}
\nh2,
h3 {
    font-size: 1.2em;
    line-height: 1.3em;
    padding: 0em;
    text-align: left !important;
}
\nh4,
h5,
h6 {
    font-size: 1.1em;
    line-height: 1.3em;
    padding: 0 0 0.1em;
}
\ntable {
    width: 100% !important;
}
\na.read-article {
    font-size: 12px;
    margin: 0 0 0 12px;
}
\np {
    padding: 0 0 0.1em;
}
\nul,
ol {
    margin: 0em;
    margin-left: -20px;
}
\nol {
    margin-left: 0px;
}
\nul li {
    position: relative;
    list-style: none;
}
\nul li:before {
    content: '';
    display: block;
    position: absolute;
    left: -20px;
    top: 9px;
    width: 8px;
    height: 8px;
    overflow: hidden;
    background: #f6c608;
    border-radius: 4px;
}
\n\nli {
    padding: 0 0 0.5em;
}
\ntable .article-pic {
    margin-left: 0px;
    margin-right: 0px;
}
\n\np.adme-img-copyright {
    margin-top: -10px;
    font-size: 80%;
    font-style: italic;
    line-height: 18px;
    color: #939393;
}
\np.adme-img-copyright a {
    color: #939393;
}
\np.adme-img-description {
    margin-top: -10px;
}
\n\na {
    color: #0064af;
}
\n\n.poem-flex {
    display: flex;
    justify-content: center;
}
```
Css initially is not formatted, just one line string

**Comment by stefanhaustein** [comment]
My suspicion would be a problem resolving the percentage at root for "font: 110%/1.5em Helvetica, Arial, sans-serif;", will add a test later

**Comment by stefanhaustein** [comment]
Should be fixed at head. Code was trying to resolve the font size based on the font size; now handled properly at the inherit step. If there are still issues, please attach a full example.

**Comment by IliaEremin** [comment]
@stefanhaustein thank you for quick fix. Are you going to release this new version to gradle?

**Comment by stefanhaustein** [comment]
Should be available via com.github.stefanhaustein:htmlview2:master-SNAPSHOT already.

**Comment by stefanhaustein** [comment]
p.s. does this work for you?
